ALTER TABLE kitchens ADD COLUMN IF NOT EXISTS slug text;

DO $$
DECLARE
  item record;
  base text;
  candidate text;
  suffix integer;
BEGIN
  -- Replace only the numeric slugs generated by the previous migration.
  FOR item IN SELECT id, name, slug FROM locations ORDER BY id LOOP
    base := coalesce(nullif(trim(both '-' from regexp_replace(lower(item.name), '[^a-z0-9]+', '-', 'g')), ''), 'location');
    IF item.slug IS NULL OR item.slug = '' OR item.slug = base || '-' || item.id THEN
      candidate := base;
      suffix := 2;
      WHILE EXISTS (SELECT 1 FROM locations WHERE slug = candidate AND id <> item.id) LOOP
        candidate := base || '-' || suffix;
        suffix := suffix + 1;
      END LOOP;
      UPDATE locations SET slug = candidate WHERE id = item.id;
    END IF;
  END LOOP;

  FOR item IN SELECT id, location_id, name FROM kitchens WHERE slug IS NULL OR slug = '' ORDER BY location_id, id LOOP
    base := coalesce(nullif(trim(both '-' from regexp_replace(lower(item.name), '[^a-z0-9]+', '-', 'g')), ''), 'kitchen');
    candidate := base;
    suffix := 2;
    WHILE EXISTS (SELECT 1 FROM kitchens WHERE location_id = item.location_id AND slug = candidate AND id <> item.id) LOOP
      candidate := base || '-' || suffix;
      suffix := suffix + 1;
    END LOOP;
    UPDATE kitchens SET slug = candidate WHERE id = item.id;
  END LOOP;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS kitchens_location_slug_unique ON kitchens (location_id, slug);
