import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import ApplicantDashboard from './ApplicantDashboard';
vi.mock('@/hooks/use-auth', () => ({ useFirebaseAuth: () => ({ user: { uid: 'fixture-chef', role: 'chef', isChef: true } }) }));
vi.mock('@/lib/firebase', () => ({ auth: { currentUser: { getIdToken: async () => 'fixture-token' } } }));
vi.mock('@/lib/queryClient', () => ({ queryClient: { invalidateQueries: vi.fn() } }));
vi.mock('@tanstack/react-query', () => ({ useQuery: () => ({ data: [], isLoading: false, refetch: vi.fn() }) }));
vi.mock('@/hooks/use-chef-kitchen-applications', () => ({ useChefKitchenApplications: () => ({ applications: [] }) }));
vi.mock('@/hooks/use-kitchen-bookings', () => ({ useKitchenBookings: () => ({ bookings: [], kitchens: [], cancelBooking: { mutate: vi.fn() } }) }));
vi.mock('@/hooks/use-chef-onboarding-status', () => ({ useChefOnboardingStatus: () => ({ showSetupBanner: false }) }));
vi.mock('@/hooks/use-chef-resolution-center', () => ({ useChefResolutionCenter: () => ({ hasAnyItems: false, pendingDamageClaims: [], pendingPenalties: [] }) }));
vi.mock('@/hooks/use-chef-sidebar-hidden-items', () => ({ useChefSidebarHiddenItems: () => [] }));
vi.mock('@/hooks/use-subdomain', () => ({ useSubdomain: () => null }));
vi.mock('@/layouts/chef-shell-context', () => ({ useChefShellChrome: () => false }));
vi.mock('@/components/ui/custom-alerts', () => ({ useCustomAlerts: () => ({ showConfirm: vi.fn() }) }));
vi.mock('react-i18next', async importOriginal => ({ ...await importOriginal<typeof import('react-i18next')>(), useTranslation: () => ({ t: (key: string) => key === 'shellKitchenTours' ? 'Kitchen tours' : key }) }));
vi.mock('@/components/chef/seller-revenue/hooks/useSellerRevenue', () => ({ useShopStatus: () => ({ data: null }) }));
vi.mock('@/components/chat/ChatPanel', () => ({ default: () => null }));
vi.mock('@/components/chat/UnifiedChatView', () => ({ default: () => null }));
vi.mock('@/components/booking/ChefBookingsView', () => ({ default: () => null }));
vi.mock('@/components/booking/PendingStorageExtensions', () => ({ PendingStorageExtensions: () => null }));
vi.mock('@/components/chef/ChefCommandPalette', () => ({ default: () => null }));
vi.mock('@/components/training/TrainingOverviewPanel', () => ({ default: () => null }));
vi.mock('@/components/application/ApplicationFormPanel', () => ({ default: () => null }));
vi.mock('@/components/document-verification/DocumentUpload', () => ({ DocumentManagementModal: () => null }));
vi.mock('@/components/application/ApplicationFormContext', () => ({ leaveSellerApplication: () => {} }));
vi.mock('@/components/chef/ChefSupportPage', () => ({ default: () => null }));
vi.mock('@/components/chef/IssuesAndRefunds', () => ({ IssuesAndRefunds: () => null }));
vi.mock('@/components/chef/TransactionHistory', () => ({ TransactionHistory: () => null }));
vi.mock('@/components/chat/TidioController', () => ({ default: () => null }));
vi.mock('@/components/chef/OutstandingDuesBanner', () => ({ default: () => null }));
vi.mock('@/components/chef/ChefProfileSettings', () => ({ default: () => null }));
vi.mock('@/components/chef/seller-revenue/ChefSellerRevenue', () => ({ default: () => null }));
vi.mock('@/components/chef/ChefSellerAccount', () => ({ default: () => null }));
vi.mock('@/components/chef/ChefNotificationCenter', () => ({ default: () => null }));
vi.mock('@/components/chef/ui', () => ({ ChefPageHeader: () => null }));
vi.mock('@/components/chef/dashboard', () => ({ OverviewTabContent: () => null, MyKitchensTabContent: () => null, SellerApplicationTabContent: () => null, getTrainingStatusLabel: () => "" }));
vi.mock('@/components/kitchen-application/KitchenDiscovery', () => ({ default: () => <div>Kitchen discovery content</div> }));
vi.mock('@/layouts/ChefDashboardLayout', () => ({ default: ({ breadcrumbs, children }: any) => <><nav aria-label="Breadcrumb">{breadcrumbs.map((crumb: any) => crumb.onClick ? <button key={crumb.label} onClick={crumb.onClick}>{crumb.label}</button> : <span key={crumb.label}>{crumb.label}</span>)}</nav>{children}</> }));
afterEach(() => { cleanup(); window.history.replaceState({}, '', '/'); });
it('places a directly linked chef tour beneath Kitchen tours and clears detail and email action through its parent breadcrumb', async () => {
  window.history.replaceState({}, '', '/dashboard?view=viewings&viewing=77&action=cancel');
  render(<ApplicantDashboard />);
  const parent = await screen.findByRole('button', { name: 'Kitchen tours' });
  expect(screen.getByRole('navigation', { name: 'Breadcrumb' })).toHaveTextContent('Kitchen toursTOUR-77');
  fireEvent.click(parent);
  await waitFor(() => expect(window.location.search).toBe('?view=viewings'));
  expect(screen.queryByText('TOUR-77')).not.toBeInTheDocument();
  expect(screen.getByText('Kitchen tours')).toBeInTheDocument();
});

it('links a full-page application under My Kitchen Applications and returns to the table from its breadcrumb', async () => {
  window.history.replaceState({}, '', '/dashboard?view=kitchen-requests&application=57');
  render(<ApplicantDashboard />);
  const parent = await screen.findByRole('button', { name: 'shellMyKitchenApplications' });
  expect(screen.getByRole('navigation', { name: 'Breadcrumb' })).toHaveTextContent('APPLICATION-57');
  fireEvent.click(parent);
  await waitFor(() => expect(window.location.search).toBe('?view=kitchen-requests'));
  expect(screen.queryByText('APPLICATION-57')).not.toBeInTheDocument();
});
