/** npm run preview:tour-emails -- --output <directory> | local, fixture-only tour email gallery. */
import express from 'express';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { emailBrandLogoUrl, emailDarkRules } from '../server/email-theme';

// Set BEFORE importing renderers. This process never loads .env or invokes delivery.
process.env.DATABASE_URL = 'postgres://preview:preview@127.0.0.1:1/preview';
process.env.E2E_SUPPRESS_OUTBOUND = '1';
process.env.NODE_ENV = 'test';
process.env.EMAIL_USER = 'preview@example.com';
process.env.BASE_DOMAIN = 'localcooks.ca';
process.env.APP_BASE_DOMAIN = 'localcooks.ca';
process.env.VERCEL_ENV = 'production';

const applicationEmails = process.argv.includes('--applications');
const bookingEmails = process.argv.includes('--bookings');
const scopeName = bookingEmails ? 'booking' : applicationEmails ? 'application' : 'tour';
const { samples, notificationOnly } = bookingEmails
  ? (await import('./kitchen-booking-email-samples')).buildKitchenBookingEmailSamples()
  : applicationEmails
  ? (await import('./kitchen-application-email-samples')).buildKitchenApplicationEmailSamples()
  : await (await import('./tour-email-samples')).buildTourEmailSamples();
const data = JSON.stringify({ samples: samples.map((sample, index) => ({ ...sample, id: String(index) })), notificationOnly }).replace(/</g, '\\u003c');
const previewLogo = 'data:image/png;base64,' + (await readFile(path.resolve('attached_assets/emailHeader-brand-red.png'))).toString('base64');
let html = String.raw`<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Kitchen tour emails · Local Cooks</title><style>
*{box-sizing:border-box}body{margin:0;font:14px/1.5 system-ui,sans-serif;background:#f8fafc;color:#172033}button,select,input{font:inherit}button,select{cursor:pointer}button,a{touch-action:manipulation}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #fda4af;outline-offset:2px}
header{padding:20px 28px;background:#fff;border-bottom:1px solid #e2e8f0;display:flex;align-items:center;gap:20px}header h1{font-size:22px;margin:0;letter-spacing:-.5px}header p{margin:3px 0 0;color:#64748b;font-size:13px}.pill{font-size:12px;border:1px solid #fecdd3;background:#fff1f2;color:#be123c;border-radius:20px;padding:6px 12px;white-space:nowrap}.layout{display:grid;grid-template-columns:330px 1fr;height:calc(100vh - 97px)}aside{border-right:1px solid #e2e8f0;background:#fff;display:flex;min-height:0;flex-direction:column}.filters{padding:16px;display:grid;gap:10px;border-bottom:1px solid #e2e8f0}.filters input,.filters select{width:100%;border:1px solid #cbd5e1;border-radius:6px;padding:9px;background:white;color:#172033}.filter-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.count{font-size:12px;color:#64748b}.list{overflow:auto;padding:8px;flex:1}.item{display:block;width:100%;text-align:left;background:white;border:1px solid transparent;border-radius:8px;padding:12px;color:#172033;margin-bottom:4px}.item:hover{background:#f8fafc}.item.active{background:#fff1f2;border-color:#fda4af}.item strong{font-size:13px;display:block}.item small{color:#64748b;display:block;margin-top:5px}.badge{display:inline-block;font-size:11px;padding:2px 6px;background:#f1f5f9;border-radius:4px;color:#475569;margin-right:6px}main{display:flex;flex-direction:column;min-width:0;min-height:0}.meta{background:white;padding:18px 24px;border-bottom:1px solid #e2e8f0}.meta h2{margin:0 0 8px;font-size:19px}.meta p{margin:3px 0;font-size:13px;color:#64748b;overflow-wrap:anywhere}.meta b{color:#334155}.tools{padding:12px 24px;display:flex;gap:8px;flex-wrap:wrap;background:white;border-bottom:1px solid #e2e8f0}.tools button{background:#fff;border:1px solid #cbd5e1;border-radius:6px;padding:7px 12px;color:#334155}.tools button.active{background:#172033;border-color:#172033;color:#fff}.tools .spacer{flex:1}.stage{padding:20px;flex:1;overflow:auto;display:flex;justify-content:center}iframe{width:100%;max-width:760px;height:100%;min-height:460px;border:1px solid #e2e8f0;border-radius:8px;background:white}iframe.mobile{width:375px;max-width:100%;flex-shrink:0}pre{margin:0;background:white;border:1px solid #e2e8f0;border-radius:8px;width:100%;max-width:950px;padding:24px;white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.7 ui-monospace,Consolas,monospace;color:#334155}.notice{border:1px solid #cbd5e1;border-radius:8px;background:white;padding:24px;max-width:760px;width:100%;align-self:flex-start}.notice h3{margin:0 0 12px}.notice li{margin:12px 0}.bottom{padding:10px 24px;color:#64748b;background:#fff;font-size:12px;border-top:1px solid #e2e8f0}details{padding:12px 16px;border-top:1px solid #e2e8f0;font-size:12px;color:#64748b}details button{border:0;background:none;text-align:left;padding:5px 0;color:#475569;display:block}
@media(max-width:850px){.layout{grid-template-columns:260px 1fr}.meta,.tools{padding-left:16px;padding-right:16px}header{padding:16px}.stage{padding:10px}}@media(max-width:620px){header{display:block}header .pill{display:inline-block;margin-top:10px}.layout{height:auto;display:block}aside{max-height:310px;border-right:0;border-bottom:1px solid #e2e8f0}.stage{min-height:650px}iframe{height:900px}.bottom{padding:10px 16px}}
</style></head><body><header><div style="flex:1"><h1>Kitchen tour emails</h1><p>Current workspace templates · real renderers · fictional people and tour details</p></div><span class="pill">Preview only · no email sent</span></header>
<div class="layout"><aside><div class="filters"><input id="search" aria-label="Search emails" placeholder="Search scenarios, subjects or names"><div class="filter-row"><select id="role" aria-label="Recipient"><option value="">All recipients</option><option>Chef</option><option>Manager</option><option>Local Cooks</option></select><select id="group" aria-label="Email group"><option value="">All scenarios</option></select></div><span class="count" id="count"></span></div><nav class="list" id="list" aria-label="Tour email scenarios"></nav><details><summary>Events that do not send email</summary><div id="no-email"></div></details></aside>
<main><div class="meta"><h2 id="scenario"></h2><p id="subject"></p><p id="recipient"></p></div><div class="tools"><button data-mode="html" class="active">Email</button><button data-mode="text">Plain text</button><button data-mode="source">HTML source</button><button data-mode="links">Links</button><span class="spacer"></span><button id="mobile" aria-pressed="false">Mobile</button><button id="theme">Dark preview</button><button id="download">Download HTML</button><button id="calendar" hidden>Download calendar</button></div><div class="stage" id="stage"></div><div class="bottom">Links are listed for inspection. The email preview cannot open destinations or send messages.</div></main></div>
<script>
const darkStyles=${JSON.stringify(emailDarkRules)};const logoUrl=${JSON.stringify(emailBrandLogoUrl)},previewLogo=${JSON.stringify(previewLogo)};const {samples,notificationOnly}=${data};let selected=0,mode='html',mobile=false,emailTheme='light';
const el=id=>document.getElementById(id);const groups=[...new Set(samples.map(s=>s.group))];for(const group of groups){const option=document.createElement('option');option.textContent=group;el('group').append(option)}
function filtered(){const q=el('search').value.toLowerCase();return samples.filter(s=>(!el('role').value||s.role===el('role').value)&&(!el('group').value||s.group===el('group').value)&&[s.scenario,s.subject,s.to,s.text].join(' ').toLowerCase().includes(q))}
function list(){const visible=filtered();el('list').replaceChildren();el('count').textContent=visible.length+' of '+samples.length+' emails';for(const s of visible){const b=document.createElement('button');b.className='item'+(s.id===String(selected)?' active':'');b.dataset.sample=s.id;b.setAttribute('aria-current',s.id===String(selected)?'true':'false');const strong=document.createElement('strong');strong.textContent=s.scenario;const small=document.createElement('small');const badge=document.createElement('span');badge.className='badge';badge.textContent=s.role;small.append(badge,document.createTextNode(s.group));b.append(strong,small);b.onclick=()=>{selected=Number(s.id);list();show()};el('list').append(b)}if(!visible.length){el('list').textContent='No matching emails.'}return visible}
function links(s){const d=new DOMParser().parseFromString(s.html,'text/html');return Array.from(d.querySelectorAll('a')).map(a=>a.textContent.trim()+'\n'+a.getAttribute('href')).join('\n\n')}
function show(){const s=samples[selected];el('scenario').textContent=s.scenario;el('subject').textContent='Subject: '+s.subject;el('recipient').textContent='To: '+s.to+' · '+s.role+' · '+s.group;el('stage').replaceChildren();if(mode==='html'){const frame=document.createElement('iframe');frame.title=s.scenario+' email preview';frame.setAttribute('sandbox','');frame.srcdoc=s.html.replaceAll(logoUrl,previewLogo).replace('@media(prefers-color-scheme:dark)','@media(min-width:99999px)').replace('</head>',(emailTheme==='dark'?'<style>'+darkStyles+'</style>':'')+'</head>');frame.style.colorScheme=emailTheme;frame.className=mobile?'mobile':'';el('stage').append(frame)}else{const p=document.createElement('pre');p.textContent=mode==='text'?s.text:mode==='source'?s.html:links(s);el('stage').append(p)}document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));el('download').textContent='Download '+(mode==='html'||mode==='source'?'HTML':mode==='links'?'links':'text');el('calendar').hidden=!s.attachments.length;el('mobile').classList.toggle('active',mobile);el('mobile').setAttribute('aria-pressed',String(mobile))}
for(const id of ['search','role','group'])el(id).addEventListener(id==='search'?'input':'change',()=>{const visible=list();if(visible.length&&!visible.some(s=>s.id===String(selected))){selected=Number(visible[0].id);list();show()}});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;show()});el('mobile').onclick=()=>{mobile=!mobile;mode='html';show()};
el('theme').onclick=()=>{emailTheme=emailTheme==='light'?'dark':'light';el('theme').textContent=emailTheme==='dark'?'Light preview':'Dark preview';show()};
function save(content,type,name){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
el('download').onclick=()=>{const s=samples[selected],isHtml=mode==='html'||mode==='source';save(isHtml?s.html:mode==='links'?links(s):s.text,isHtml?'text/html':'text/plain',s.id+'-'+s.scenario.toLowerCase().replace(/[^a-z0-9]+/g,'-')+(isHtml?'.html':'.txt'))};el('calendar').onclick=()=>{for(const a of samples[selected].attachments)save(a.content,'text/calendar',a.filename)};
for(const n of notificationOnly){const b=document.createElement('button');b.textContent=n.scenario+' · '+[...new Set(n.recipients)].join(', ');b.onclick=()=>{el('stage').replaceChildren();const box=document.createElement('div');box.className='notice';const h=document.createElement('h3');h.textContent=n.scenario;const p=document.createElement('p');p.textContent='This event sends in-app notifications to '+[...new Set(n.recipients)].join(', ')+'. It does not generate an email.';box.append(h,p);el('stage').append(box);el('scenario').textContent=n.scenario;el('subject').textContent='No email is sent';el('recipient').textContent='In-app notifications only';el('download').disabled=true;el('calendar').hidden=true};el('no-email').append(b)}
document.addEventListener('keydown',e=>{if(!['ArrowDown','ArrowUp'].includes(e.key)||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;const visible=filtered(),i=visible.findIndex(s=>s.id===String(selected)),next=visible[i+(e.key==='ArrowDown'?1:-1)];if(next){e.preventDefault();selected=Number(next.id);list();show();document.querySelector('.item.active').scrollIntoView({block:'nearest'})}});const showEmail=show;show=function(){el('download').disabled=false;showEmail()};list();show();
</script></body></html>`;

if (scopeName !== 'tour') html = html.replace(/Kitchen tour/g, 'Kitchen ' + scopeName).replace(/kitchen tour/g, 'kitchen ' + scopeName).replace(/Tour email/g, scopeName === 'booking' ? 'Booking email' : 'Application email').replace('people and tour details', 'people and ' + scopeName + ' details');
const outputName = 'kitchen-' + scopeName;
const outputIndex = process.argv.indexOf('--output');
if (outputIndex >= 0) {
  const directory = path.resolve(process.argv[outputIndex + 1]);
  await mkdir(directory, { recursive: true });
  await writeFile(path.join(directory, outputName + '-emails.html'), html);
  await writeFile(path.join(directory, outputName + '-email-samples.json'), JSON.stringify({ samples, notificationOnly }, null, 2));
  console.log(`Saved standalone preview to ${directory}`);
}
if (!process.argv.includes('--export-only')) {
  const app = express();
  app.get('/', (_request, response) => response.type('html').send(html));
  app.get('/samples.json', (_request, response) => response.json({ samples, notificationOnly }));
  const port = Number(process.env.TOUR_EMAIL_PREVIEW_PORT || 3848);
  app.listen(port, '127.0.0.1', () => console.log(`${samples.length} ${scopeName} emails · http://127.0.0.1:${port}`));
} else console.log(`Exported ${samples.length} ${scopeName} emails and ${notificationOnly.length} notification-only scenarios.`);
