const fs=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');const ts=require('typescript');
const source=fs.readFileSync('server/routes/manager.ts','utf8').replace(/\r\n/g,'\n');const handlers={};let tail=Promise.resolve(),record,locks=0;
const service={findPaymentTransactionById:async(_id,tx)=>structuredClone(tx.record),updatePaymentTransaction:async(_id,patch,tx)=>Object.assign(tx.record,patch),addPaymentHistory:async()=>{}};
const db={transaction:async fn=>{const prior=tail;let release;tail=new Promise(r=>release=r);await prior;const tx={record:structuredClone(record),execute:async()=>{locks++}};try{const result=await fn(tx);record=tx.record;return result}finally{release()}}};
const globals={router:{post:(path,...args)=>handlers[path]=args.at(-1)},db,requireFirebaseAuthWithUser:()=>{},requireManager:()=>{},sql:()=>'',logger:{error:()=>{}},errorResponse:(res,e)=>res.status(500).json({error:e.message}),require:path=>{assert.ok(path.includes('payment-transactions'),'No Stripe operation should run');return service}};
for(const route of ['refund','full-refund-request']){const a=source.indexOf('router.post(\n  "/revenue/transactions/:transactionId/'+route+'",');const b=source.indexOf('\n);',a)+4;assert.ok(a>=0&&b>a);vm.runInNewContext(ts.transpileModule(source.slice(a,b),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,globals)}
function reset(){record={id:1,booking_id:40,booking_type:'bundle',manager_id:3,status:'succeeded',amount:'10000',refund_amount:'0',stripe_processing_fee:'300',manager_revenue:'9000',service_fee:'700',payment_intent_id:'pi_test',metadata:{}};locks=0;tail=Promise.resolve()}
async function call(route,managerId=3){const res={code:200,headersSent:false,status(n){this.code=n;return this},json(body){this.body=body;this.headersSent=true;return this}};await handlers['/revenue/transactions/:transactionId/'+route]({neonUser:{id:managerId},params:{transactionId:'1'},body:{amount:100,reason:'Chef cancellation'}},res);return res}
(async()=>{reset();const results=await Promise.all([call('full-refund-request'),call('full-refund-request')]);assert.deepEqual(results.map(x=>x.code).sort(),[201,409]);assert.equal(locks,2);assert.equal(record.metadata.fullRefundRequest.status,'pending');assert.equal((await call('refund')).code,409);reset();assert.equal((await call('full-refund-request',99)).code,403);assert.equal(record.metadata.fullRefundRequest,undefined);console.log('Manager refund flow: duplicate requests, ownership and pending-review protection passed.')})().catch(e=>{console.error(e);process.exitCode=1});

