import type { ComponentType } from "react";
import { addCollection, Icon, type IconProps } from "@iconify/react";
import { icons as mdiIcons } from "@iconify-json/mdi";

addCollection(mdiIcons);

type ManagerIconProps = Omit<IconProps, "icon"> & {
  absoluteStrokeWidth?: boolean;
  size?: number | string;
  strokeWidth?: number;
};

function managerIcon(icon: string): ComponentType<ManagerIconProps> {
  function ManagerIcon({ absoluteStrokeWidth: _absolute, size, strokeWidth: _stroke, ...props }: ManagerIconProps) {
    return <Icon icon={icon} width={props.width ?? size} height={props.height ?? size} aria-hidden {...props} />;
  }

  ManagerIcon.displayName = `ManagerIcon(${icon})`;
  return ManagerIcon;
}

export const AlertCircle = managerIcon("mdi:alert-circle-outline");
export const AlertTriangle = managerIcon("mdi:alert-outline");
export const AlignLeft = managerIcon("mdi:format-align-left");
export const Archive = managerIcon("mdi:archive-outline");
export const ArrowRight = managerIcon("mdi:arrow-right");
export const ArrowUpDown = managerIcon("mdi:swap-vertical");
export const BadgeCheck = managerIcon("mdi:badge-account-outline");
export const Ban = managerIcon("mdi:cancel");
export const Banknote = managerIcon("mdi:cash");
export const BarChart3 = managerIcon("mdi:chart-bar");
export const Bell = managerIcon("mdi:bell-outline");
export const BellOff = managerIcon("mdi:bell-off-outline");
export const BookOpen = managerIcon("mdi:book-open-variant");
export const Boxes = managerIcon("mdi:archive-marker-outline");
export const Briefcase = managerIcon("mdi:briefcase-outline");
export const Building = managerIcon("mdi:office-building");
export const Building2 = managerIcon("mdi:office-building-outline");
export const Calendar = managerIcon("mdi:calendar-outline");
export const CalendarClock = managerIcon("mdi:calendar-clock-outline");
export const CalendarDays = managerIcon("mdi:calendar-month-outline");
export const CalendarIcon = Calendar;
export const Camera = managerIcon("mdi:camera-outline");
export const Check = managerIcon("mdi:check");
export const CheckCheck = managerIcon("mdi:check-all");
export const CheckCircle = managerIcon("mdi:check-circle-outline");
export const CheckCircle2 = CheckCircle;
export const CheckSquare = managerIcon("mdi:checkbox-marked-outline");
export const ChevronDown = managerIcon("mdi:chevron-down");
export const ChevronLeft = managerIcon("mdi:chevron-left");
export const ChevronRight = managerIcon("mdi:chevron-right");
export const ChevronUp = managerIcon("mdi:chevron-up");
export const ChevronsUpDown = managerIcon("mdi:unfold-more-horizontal");
export const Circle = managerIcon("mdi:circle-outline");
export const CircleDollarSign = managerIcon("mdi:cash-multiple");
export const ClipboardCheck = managerIcon("mdi:clipboard-check-outline");
export const ClipboardList = managerIcon("mdi:clipboard-text-outline");
export const Clock = managerIcon("mdi:clock-outline");
export const Cloud = managerIcon("mdi:cloud-outline");
export const CookingPot = managerIcon("mdi:pot-steam-outline");
export const Copy = managerIcon("mdi:content-copy");
export const CreditCard = managerIcon("mdi:credit-card-outline");
export const DollarSign = managerIcon("mdi:currency-usd");
export const Download = managerIcon("mdi:download");
export const Edit = managerIcon("mdi:pencil-outline");
export const Edit2 = Edit;
export const Edit3 = Edit;
export const ExternalLink = managerIcon("mdi:open-in-new");
export const Eye = managerIcon("mdi:eye-outline");
export const EyeOff = managerIcon("mdi:eye-off-outline");
export const File = managerIcon("mdi:file-outline");
export const FileCheck = managerIcon("mdi:file-check-outline");
export const FileSpreadsheet = managerIcon("mdi:file-excel-outline");
export const FileText = managerIcon("mdi:file-document-outline");
export const FileWarning = managerIcon("mdi:file-alert-outline");
export const Filter = managerIcon("mdi:filter-outline");
export const Flame = managerIcon("mdi:fire");
export const FolderOpen = managerIcon("mdi:folder-open-outline");
export const Globe = managerIcon("mdi:earth");
export const Grid3X3 = managerIcon("mdi:view-grid-outline");
export const GripVertical = managerIcon("mdi:drag-vertical");
export const Handshake = managerIcon("mdi:handshake-outline");
export const Hash = managerIcon("mdi:pound");
export const HelpCircle = managerIcon("mdi:help-circle-outline");
export const History = managerIcon("mdi:history");
export const Home = managerIcon("mdi:home-outline");
export const Image = managerIcon("mdi:image-outline");
export const ImageIcon = Image;
export const ImagePlus = managerIcon("mdi:image-plus-outline");
export const Info = managerIcon("mdi:information-outline");
export const KeyRound = managerIcon("mdi:key-outline");
export const LayoutDashboard = managerIcon("mdi:view-dashboard-outline");
export const ListChecks = managerIcon("mdi:format-list-checks");
export const Loader2 = managerIcon("mdi:loading");
export const Lock = managerIcon("mdi:lock-outline");
export const LogIn = managerIcon("mdi:login");
export const LogOut = managerIcon("mdi:logout");
export const Mail = managerIcon("mdi:email-outline");
export const MapPin = managerIcon("mdi:map-marker-outline");
export const Menu = managerIcon("mdi:menu");
export const MessageCircle = managerIcon("mdi:message-text-outline");
export const MessageSquare = managerIcon("mdi:message-outline");
export const MoreHorizontal = managerIcon("mdi:dots-horizontal");
export const Package = managerIcon("mdi:package-variant-closed");
export const PackageCheck = managerIcon("mdi:package-check");
export const PartyPopper = managerIcon("mdi:party-popper");
export const Percent = managerIcon("mdi:percent");
export const Pencil = managerIcon("mdi:pencil");
export const Phone = managerIcon("mdi:phone-outline");
export const Plus = managerIcon("mdi:plus");
export const PlusCircle = managerIcon("mdi:plus-circle-outline");
export const Receipt = managerIcon("mdi:receipt-text-outline");
export const RefreshCcw = managerIcon("mdi:refresh");
export const RefreshCw = RefreshCcw;
export const Rocket = managerIcon("mdi:rocket-launch-outline");
export const RotateCcw = managerIcon("mdi:restore");
export const Save = managerIcon("mdi:content-save-outline");
export const Search = managerIcon("mdi:magnify");
export const SearchX = managerIcon("mdi:magnify-remove-outline");
export const Send = managerIcon("mdi:send-outline");
export const Settings = managerIcon("mdi:cog-outline");
export const Settings2 = managerIcon("mdi:tune-variant");
export const Shield = managerIcon("mdi:shield-outline");
export const ShieldAlert = managerIcon("mdi:shield-alert-outline");
export const ShieldCheck = managerIcon("mdi:shield-check-outline");
export const SkipForward = managerIcon("mdi:skip-forward-outline");
export const Snowflake = managerIcon("mdi:snowflake");
export const SprayCan = managerIcon("mdi:spray-bottle");
export const Star = managerIcon("mdi:star-outline");
export const Storefront = managerIcon("mdi:storefront-outline");
export const Thermometer = managerIcon("mdi:thermometer");
export const Timer = managerIcon("mdi:timer-outline");
export const Trash2 = managerIcon("mdi:delete-outline");
export const TrendingDown = managerIcon("mdi:trending-down");
export const TrendingUp = managerIcon("mdi:trending-up");
export const Type = managerIcon("mdi:format-text");
export const Upload = managerIcon("mdi:upload");
export const User = managerIcon("mdi:account-outline");
export const Users = managerIcon("mdi:account-group-outline");
export const UtensilsCrossed = managerIcon("mdi:silverware-fork-knife");
export const Wallet = managerIcon("mdi:wallet-outline");
export const Wind = managerIcon("mdi:weather-windy");
export const Wrench = managerIcon("mdi:wrench-outline");
export const X = managerIcon("mdi:close");
export const XCircle = managerIcon("mdi:close-circle-outline");
export const Zap = managerIcon("mdi:lightning-bolt-outline");
export const ArchiveCheck = managerIcon("mdi:archive-check-outline");
